version: 1.2
workflows:
 - name: SS2_scRNA_pipeline
   subclass: WDL
   primaryDescriptorPath: /wdl/SS2_scRNA_pipeline.wdl
   testParameterFiles:
   - /input_json/ss2_scRNA_pipeline_inputs.json
 - name: SC_Plate_QC
   subclass: WDL
   primaryDescriptorPath: /wdl/SC_Plate_QC.wdl
   testParameterFiles:
   - /input_json/SC_Plate_QC_pipeline_inputs.json
 - name: ichorCNA_step1
   subclass: WDL
   primaryDescriptorPath: /wdl/ichorCNA_step1.wdl
   testParameterFiles:
   - /input_json/ichorCNA_step1_pipeline_inputs.json
 - name: ichorCNA_step2
   subclass: WDL
   primaryDescriptorPath: /wdl/ichorCNA_step2.wdl
   testParameterFiles:
   - /input_json/ichorCNA_step2_pipeline_inputs.json
 - name: cnv_somatic_pair_workflow
   subclass: WDL
   primaryDescriptorPath: /wdl/cnv_somatic_pair_workflow.wdl
   testParameterFiles:
   - /input_json/cnv_somatic_pair_workflow_inputs.json