version: 1.2
workflows:
 - name: SS2_scRNA_pipeline
   subclass: WDL
   primaryDescriptorPath: /wdl/SS2_scRNA_pipeline.wdl
   testParameterFiles:
   - /input_json/ss2_scRNA_pipeline_inputs.json
   filter: 
     - SS2_scRNA_pipeline*
 - name: SC_Plate_QC
   subclass: WDL
   primaryDescriptorPath: /wdl/SC_Plate_QC.wdl
   testParameterFiles:
   - /input_json/SC_Plate_QC_pipeline_inputs.json
   filter: 
     - SC_Plate_QC*
