version: 1.2
workflows:
 - name: SmartSeq2_scRNA_pipeline
   subclass: WDL
   primaryDescriptorPath: /SmartSeq/scRNA_Pipeline/SmartSeq2_scRNA_pipeline.wdl
   testParameterFiles:
   - /SmartSeq/scRNA_Pipeline/SmartSeq2_scRNA_pipeline.human.terra-inputs.json
   - /SmartSeq/scRNA_Pipeline/SmartSeq2_scRNA_pipeline.mouse.terra-inputs.json
 - name: SmartSeq2_SC_Plate_QC
   subclass: WDL
   primaryDescriptorPath: /SmartSeq/SC_Plate_QC/SC_Plate_QC.wdl
   testParameterFiles:
   - /SmartSeq/SC_Plate_QC/SC_Plate_QC.human.terra-inputs.json
   - /SmartSeq/SC_Plate_QC/SC_Plate_QC.mouse.terra-inputs.json
 - name: CollectSamErrorMetrics
   subclass: WDL
   primaryDescriptorPath: /CollectSamError/CollectSamErrorMetrics.wdl
   testParameterFiles:
   - /CollectSamError/CollectSamErrorMetrics.inputs.json
 - name: GATK4_CNV
   subclass: WDL
   primaryDescriptorPath: /GATK_CNV_Mutect2/GATK4_CNV/GATK4_CNV.wdl
   testParameterFiles:
   - /GATK_CNV_Mutect2/GATK4_CNV/GATK4_CNV.inputs.json
 - name: mutect2-gatk4
   subclass: WDL
   primaryDescriptorPath: /GATK_CNV_Mutect2/mutect2-gatk4/mutect2-gatk4.wdl
   testParameterFiles:
   - /Users/gaoyueya/Documents/GitHub/TAG-public/GATK_CNV_Mutect2/mutect2-gatk4/mutect2-gatk4.inputs.json
 - name: GenerateDuplexConsensusBams
   subclass: WDL
   primaryDescriptorPath: /Liquid_Biopsy_Duplex_Analysis/GenerateDuplexConsensusBams/GenerateDuplexConsensusBams.wdl
   testParameterFiles:
   - /Liquid_Biopsy_Duplex_Analysis/GenerateDuplexConsensusBams/GenerateDuplexConsensusBams.inputs.json
 - name: MakeCallsFromConsensus
   subclass: WDL
   primaryDescriptorPath: /Liquid_Biopsy_Duplex_Analysis/MakeCallsFromConsensus/MakeCallsFromConsensus.wdl
   testParameterFiles:
   - /Liquid_Biopsy_Duplex_Analysis/MakeCallsFromConsensus/MakeCallsFromConsensus.T-N.inputs.json
   - /Liquid_Biopsy_Duplex_Analysis/MakeCallsFromConsensus/MakeCallsFromConsensus.T-only.inputs.json
 - name: iChorCNA_hg19
   subclass: WDL
   primaryDescriptorPath: /iChor/iChorCNA_hg19/iChorCNA_hg19.wdl
   testParameterFiles:
   - /iChor/iChorCNA_hg19/iChorCNA_hg19.inputs.json
 - name: iChorCNA_hg38
   subclass: WDL
   primaryDescriptorPath: /iChor/iChorCNA_hg38/iChorCNA_hg38.wdl
   testParameterFiles:
   - /iChor/iChorCNA_hg38/iChorCNA_hg38.inputs.json
 - name: iChorCNA_step2
   subclass: WDL
   primaryDescriptorPath: /iChor/iChorCNA_step2/iChorCNA_step2.wdl
   testParameterFiles:
   - /iChor/iChorCNA_step2/iChorCNA_step2.inputs.json
 - name: lego_plotter
   subclass: WDL
   primaryDescriptorPath: /LegoPlotter/lego_plotter.wdl
   testParameterFiles:
   - /LegoPlotter/lego_plotter.inputs.json
 - name: SomaticSV_SvABA
   subclass: WDL
   primaryDescriptorPath: /SomaticSV_SvABA/SomaticSV_SvABA.wdl
   testParameterFiles:
   - /SomaticSV_SvABA/SomaticSV_SvABA.inputs.json
   - /SomaticSV_SvABA/SomaticSV_SvABA_Tonly.inputs.json
 - name: BreaKmer
   subclass: WDL
   primaryDescriptorPath: /BreaKmer/BreaKmer.wdl
   testParameterFiles:
   - /BreaKmer/BreaKmer.inputs.json
 - name: Griffin_GC_Correction
   subclass: WDL
   primaryDescriptorPath: /Griffin/griffin_GC_correction/griffin_GC_correction.wdl
   testParameterFiles:
   - /Griffin/griffin_GC_correction/griffin_GC_correction.inputs.json
 - name: Griffin_Nucleosome_Profiling
   subclass: WDL
   primaryDescriptorPath: /Griffin/griffin_nucleosome_profiling/griffin_nucleosome_profiling.wdl
   testParameterFiles:
   - /Griffin/griffin_nucleosome_profiling/griffin_nucleosome_profiling.inputs.json
 - name: griffin_ER_classifier
   subclass: WDL
   primaryDescriptorPath: /Griffin/griffin_ER_classifier/griffin_ER_classifier.wdl
   testParameterFiles:
   - /Griffin/griffin_ER_classifier/griffin_ER_classifier.inputs.json
 - name: checkBaitSetName
   subclass: WDL
   primaryDescriptorPath: /checkBaitSetName/checkBaitSetName.wdl
   testParameterFiles:
    - /checkBaitSetName/checkBaitSetName.inputs.json
 - name: SelectSampleFromCallSet
   subclass: WDL
   primaryDescriptorPath: /BenchmarkCNV/SelectSampleFromCallSet/SelectSampleFromCallSet.wdl
   testParameterFiles:
   - /BenchmarkCNV/SelectSampleFromCallSet/SelectSampleFromCallSet.inputs.json
 - name: MergeVCF
   subclass: WDL
   primaryDescriptorPath: /BenchmarkCNV/MergeVCF/MergeVCF.wdl
   testParameterFiles:
   - /BenchmarkCNV/MergeVCF/MergeVCF.inputs.json
 - name: BenchmarkCNV
   subclass: WDL
   primaryDescriptorPath: /BenchmarkCNV/BenchmarkCNV/BenchmarkCNV.wdl
   testParameterFiles:
   - /BenchmarkCNV/BenchmarkCNV/BenchmarkCNV.inputs.json
 - name: checkBaitSetName_dev
   subclass: WDL
   primaryDescriptorPath: /checkBaitSetName/checkBaitSetName.dev.wdl
   testParameterFiles:
    - /checkBaitSetName/checkBaitSetName.dev.inputs.json
 - name: DownsampleBam
   subclass: WDL
   primaryDescriptorPath: /DownsampleBam/DownsampleBam.wdl
   testParameterFiles:
    - /DownsampleBam/DownsampleBam.inputs.json
 - name: AnnotateBed_hg38
   subclass: WDL
   primaryDescriptorPath: /AnnotateBed/integrated_annotation.wdl
   testParameterFiles:
    - /AnnotateBed/AnnotateBed.inputs.json
- name: AnnotateBed_hg19
   subclass: WDL
   primaryDescriptorPath: /AnnotateBed/integrated_annotation.hg19.wdl
   testParameterFiles:
    - /AnnotateBed/AnnotateBed.inputs.json
   
