version: 1.2
workflows:
 - name: SS2_scRNA_pipeline
   subclass: WDL
   primaryDescriptorPath: /wdl/SS2_scRNA_pipeline.wdl
   testParameterFiles:
   - /input_json/ss2_scRNA_pipeline_inputs.json
 - name: SC_Plate_QC
   subclass: WDL
   primaryDescriptorPath: /wdl/SC_Plate_QC.wdl
   testParameterFiles:
   - /input_json/SC_Plate_QC_pipeline_inputs.json
 - name: CramToBam
   subclass: WDL
   primaryDescriptorPath: /wdl/CramToBam.wdl
   testParameterFiles:
   - /input_json/CramToBam_inputs.json
 - name: CollectSamErrorMetrics
   subclass: WDL
   primaryDescriptorPath: /wdl/CollectSamErrorMetrics.wdl
   testParameterFiles:
   - /input_json/CollectSamErrorMetrics_inputs.json
 - name: BenchmarkCNV
   subclass: WDL
   primaryDescriptorPath: /BenchmarkCNV/BenchmarkCNV.wdl
   testParameterFiles:
   - /BenchmarkCNV/BenchmarkCNV_test.json
 - name: GATK4_CNV
   subclass: WDL
   primaryDescriptorPath: /GATK_CNV_Mutect2/GATK4_CNV/GATK4_CNV.wdl
   testParameterFiles:
   - /GATK_CNV_Mutect2/GATK4_CNV/GATK4_CNV.inputs.json
 - name: mutect2-gatk4
   subclass: WDL
   primaryDescriptorPath: /GATK_CNV_Mutect2/mutect2-gatk4/mutect2-gatk4.wdl
   testParameterFiles:
   - /Users/gaoyueya/Documents/GitHub/TAG-public/GATK_CNV_Mutect2/mutect2-gatk4/mutect2-gatk4.inputs.json
 - name: GenerateDuplexConsensusBams
   subclass: WDL
   primaryDescriptorPath: /Liquid_Biopsy_Duplex_Analysis/GenerateDuplexConsensusBams/GenerateDuplexConsensusBams.wdl
   testParameterFiles:
   - /Liquid_Biopsy_Duplex_Analysis/GenerateDuplexConsensusBams/GenerateDuplexConsensusBams.inputs.json
 - name: MakeCallsFromConsensus
   subclass: WDL
   primaryDescriptorPath: /Liquid_Biopsy_Duplex_Analysis/MakeCallsFromConsensus/MakeCallsFromConsensus.wdl
   testParameterFiles:
   - /Liquid_Biopsy_Duplex_Analysis/MakeCallsFromConsensus/MakeCallsFromConsensus.T-N.inputs.json
   - /Liquid_Biopsy_Duplex_Analysis/MakeCallsFromConsensus/MakeCallsFromConsensus.T-only.inputs.json
 - name: iChorCNA_hg19
   subclass: WDL
   primaryDescriptorPath: /iChor/iChorCNA_hg19/iChorCNA_hg19.wdl
   testParameterFiles:
   - /iChor/iChorCNA_hg19/iChorCNA_hg19.inputs.json
 - name: iChorCNA_hg38
   subclass: WDL
   primaryDescriptorPath: /iChor/iChorCNA_hg38/iChorCNA_hg38.wdl
   testParameterFiles:
   - /iChor/iChorCNA_hg38/iChorCNA_hg38.inputs.json
 - name: iChorCNA_step2
   subclass: WDL
   primaryDescriptorPath: /iChor/iChorCNA_step2/iChorCNA_step2.wdl
   testParameterFiles:
   - /iChor/iChorCNA_step2/iChorCNA_step2.inputs.json
 - name: lego_plotter
   subclass: WDL
   primaryDescriptorPath: /LegoPlotter/lego_plotter.wdl
   testParameterFiles:
   - /LegoPlotter/lego_plotter.inputs.json

