version: 1.2
workflows:
 - name: SS2_scRNA_pipeline
   subclass: WDL
   primaryDescriptorPath: /wdl/SS2_scRNA_pipeline.wdl
   testParameterFiles:
   - /input_json/ss2_scRNA_pipeline_inputs.json
 - name: SC_Plate_QC
   subclass: WDL
   primaryDescriptorPath: /wdl/SC_Plate_QC.wdl
   testParameterFiles:
   - /input_json/SC_Plate_QC_pipeline_inputs.json
 - name: ichorCNA_step1
   subclass: WDL
   primaryDescriptorPath: /wdl/ichorCNA_step1.wdl
   testParameterFiles:
   - /input_json/ichorCNA_step1_pipeline_inputs.json
 - name: ichorCNA_step2
   subclass: WDL
   primaryDescriptorPath: /wdl/ichorCNA_step2.wdl
   testParameterFiles:
   - /input_json/ichorCNA_step2_pipeline_inputs.json
 - name: cnv_somatic_pair_workflow
   subclass: WDL
   primaryDescriptorPath: /wdl/cnv_somatic_pair_workflow.wdl
   testParameterFiles:
   - /input_json/cnv_somatic_pair_workflow_inputs.json
 - name: GenerateDuplexConsensusBams
  subclass : WDL
  primaryDescriptorPath: /wdl/MMRF_DuplexTumorOnly/GenerateDuplexConsensusBams.wdl
  testParameterFiles:
  - /input_json/MMRF_GenerateDuplexConsensusBams.json
 - name: MakeCallsFromConsensus
  subclass : WDL
  primaryDescriptorPath: /wdl/MMRF_DuplexTumorOnly/MakeCallsFromConsensus.wdl
  testParameterFiles:
  - /input_json/MMRF_MakeCallsFromConsensus.json
 - name: GenerateReportMMRF
  subclass : WDL
  primaryDescriptorPath: /wdl/MMRF_DuplexTumorOnly/GenerateReportMMRF.wdl
  testParameterFiles:
  - /input_json/MMRF_GenerateReport.json
 - name: maf_aggregator_SNV
  subclass : WDL
  primaryDescriptorPath: /wdl/MMRF_DuplexTumorOnly/maf_aggregator_SNV.wdl
  testParameterFiles:
  - /input_json/MMRF_maf_aggregator_SNV.json
 - name: maf_aggregator_INDEL
  subclass : WDL
  primaryDescriptorPath: /wdl/MMRF_DuplexTumorOnly/maf_aggregator_INDEL.wdl
  testParameterFiles:
  - /input_json/MMRF_maf_aggregator_INDEL.json
 - name: CollectGeneStatistics
  subclass : WDL
  primaryDescriptorPath: /wdl/MMRF_DuplexTumorOnly/CollectGeneStatistics.wdl
  testParameterFiles:
  - /input_json/MMRF_CollectGeneStatistics.json
